source "https://rubygems.org"
gem "rails", "4.2.3"
gem "mysql2", "~> 0.3.13"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "bootstrap-sass"
gem "devise"
gem "nested_form"
gem "bootstrap-datepicker-rails"
gem "select2-rails"
gem "cancancan"
gem "jquery-validation-rails"
gem "i18n-js", ">= 3.0.0.rc12"
gem "config"
gem "closure_tree"
gem "simple_token_authentication", "~> 1.0"
gem "font-awesome-rails"
gem "selectize-rails"
gem "will_paginate", "3.0.7"
gem "bootstrap-will_paginate", "0.0.10"
group :development, :test do
  gem "bullet"
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
end

